/**
 * GENERATED by `scripts/build-world-map.mjs` — do not edit by hand.
 *
 * Arc endpoints projected into the dotted map's own coordinate space, so the
 * browser never has to build the map to know where a pin goes. Re-run the
 * script after changing `countries.ts`.
 */

export type MapPoint = { x: number; y: number };

/** Matches the generated SVG. The overlay shares it so no conversion is needed. */
export const MAP_VIEWBOX = "0 0 198 100";
export const MAP_SRC = "/map/world-dots.svg";

export const ARC_POINTS: { start: MapPoint; end: MapPoint; label: string }[] =
[
    {
      "start": {
        "x": 145.5,
        "y": 46.77
      },
      "end": {
        "x": 55,
        "y": 33.77
      },
      "label": "United States"
    },
    {
      "start": {
        "x": 145.5,
        "y": 46.77
      },
      "end": {
        "x": 99,
        "y": 25.11
      },
      "label": "United Kingdom"
    },
    {
      "start": {
        "x": 145.5,
        "y": 46.77
      },
      "end": {
        "x": 131.5,
        "y": 45.03
      },
      "label": "United Arab Emirates"
    },
    {
      "start": {
        "x": 145.5,
        "y": 46.77
      },
      "end": {
        "x": 126.5,
        "y": 45.03
      },
      "label": "Saudi Arabia"
    },
    {
      "start": {
        "x": 145.5,
        "y": 46.77
      },
      "end": {
        "x": 160,
        "y": 59.76
      },
      "label": "Singapore"
    },
    {
      "start": {
        "x": 145.5,
        "y": 46.77
      },
      "end": {
        "x": 188.5,
        "y": 81.41
      },
      "label": "Australia"
    },
    {
      "start": {
        "x": 145.5,
        "y": 46.77
      },
      "end": {
        "x": 96.5,
        "y": 34.64
      },
      "label": "Spain"
    },
    {
      "start": {
        "x": 145.5,
        "y": 46.77
      },
      "end": {
        "x": 111.5,
        "y": 24.25
      },
      "label": "Poland"
    },
    {
      "start": {
        "x": 145.5,
        "y": 46.77
      },
      "end": {
        "x": 117.5,
        "y": 41.57
      },
      "label": "Egypt"
    },
    {
      "start": {
        "x": 145.5,
        "y": 46.77
      },
      "end": {
        "x": 142,
        "y": 58.02
      },
      "label": "Maldives"
    },
    {
      "start": {
        "x": 145.5,
        "y": 46.77
      },
      "end": {
        "x": 52,
        "y": 32.04
      },
      "label": "Canada"
    },
    {
      "start": {
        "x": 145.5,
        "y": 46.77
      },
      "end": {
        "x": 26.5,
        "y": 36.37
      },
      "label": "San Francisco"
    }
  ];
